# Generated by Django 4.0.3 on 2022-04-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('descript', models.TextField(null=True)),
                ('tag', models.ManyToManyField(to='homepage.tag')),
            ],
        ),
    ]
